/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dstest;


import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JLabel;


/**
 *
 * @author VIETHUNG
 */
public class DIntro extends javax.swing.JPanel {

    /**
     * Creates new form DIntro
     */
    
    private static boolean playGame;
    
    private BufferedImage imgBtnPlay, imgBtnExit, imgBackground;
    
    private JLabel play, exit;
        
    
    public DIntro(){
        initComponents();
        playGame = false;
                
        play = new JLabel();
        this.add(play);
        play.setBounds(250, 550, 235, 100);
        play.addMouseListener(new MouseListener(){
            @Override
            public void mouseClicked(MouseEvent e) {
                playGame = true;
            }

            @Override
            public void mousePressed(MouseEvent e) {
                
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                
            }

            @Override
            public void mouseExited(MouseEvent e) {
               
            }
            
        });
        
        exit = new JLabel();
        this.add(exit);
        exit.setBounds(525, 550, 235, 100);
        exit.addMouseListener(new MouseListener(){
            @Override
            public void mouseClicked(MouseEvent e) {
                System.exit(0);
            }

            @Override
            public void mousePressed(MouseEvent e) {
                
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                
            }

            @Override
            public void mouseExited(MouseEvent e) {
                
            }
            
        });
        
        try{
            LoadSource();
        }catch(Exception e){
            e.printStackTrace();
        }
       
    }
    
    public void LoadSource() throws IOException{
        imgBtnPlay = ImageIO.read(new File("res/btnPlay.png"));
        imgBtnExit = ImageIO.read(new File("res/btnExit.png"));
        imgBackground = ImageIO.read(new File("res/background.png"));
    }
    
    public void paint(Graphics g){
        g.drawImage(imgBackground, 0, 0, this);
        g.drawImage(imgBtnPlay, 250, 550, this);
        g.drawImage(imgBtnExit, 525, 550, this);
        
    }
    
    public static boolean getPlay(){
        return playGame;
    }  
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
